// Offline support. precache.json (generated by tools/build-precache.mjs) lists every file
// the game needs plus a content hash; a new hash installs a fresh cache and drops the old one.
const PREFIX = 'smw-';
const BUILD = 'f39101a4a577'; // stamped by tools/build-precache.mjs so a new build reinstalls the worker

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const res = await fetch('precache.json', { cache: 'no-store' });
    const { version, files } = await res.json();
    self.__version = version;
    const cache = await caches.open(PREFIX + version);
    // Add in small batches so one slow file does not stall the whole install.
    for (let i = 0; i < files.length; i += 20) await cache.addAll(files.slice(i, i + 20));
    await cache.put('precache-version', new Response(version));
    self.skipWaiting();
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    let version = self.__version;
    if (!version) { try { version = (await (await fetch('precache.json', { cache: 'no-store' })).json()).version; } catch { /* offline: keep caches */ } }
    if (version) await Promise.all(keys.filter(k => k.startsWith(PREFIX) && k !== PREFIX + version).map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  event.respondWith((async () => {
    const cached = await caches.match(req, { ignoreSearch: true });
    if (cached) return cached;
    try {
      return await fetch(req);
    } catch {
      if (req.mode === 'navigate') return (await caches.match('index.html')) || Response.error();
      return Response.error();
    }
  })());
});
