// Offline support. precache.json (generated by tools/build-precache.mjs) lists the files the
// first level needs ("files", cached at install) and the rest ("lazy": other avatars' and areas'
// atlases, cached the first time the game fetches them). BUILD is the content hash of the whole
// build; a new build installs into a fresh cache and drops the old one once it activates.
//
// Updates wait: there is no skipWaiting(), so a tab that is already open keeps the worker (and
// cache) of the build it started with, and a new build takes over once every tab of the game has
// been closed. Mixing old modules with new data is never possible. clients.claim() only affects
// the very first visit (no previous worker), so its page is served offline straight away.
const PREFIX = 'smw-';
const BUILD = '27895459a811'; // stamped by tools/build-precache.mjs so a new build reinstalls the worker
const CACHE = PREFIX + BUILD;
const RUNTIME = /\/data\//;    // same-origin paths cached on first use

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const res = await fetch(`precache.json?v=${BUILD}`, { cache: 'no-store' });
    const { files } = await res.json();
    const cache = await caches.open(CACHE);
    // Add in small batches so one slow file does not stall the whole install.
    for (let i = 0; i < files.length; i += 20) await cache.addAll(files.slice(i, i + 20));
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k.startsWith(PREFIX) && k !== CACHE).map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', event => {
  const req = event.request;
  const url = new URL(req.url);
  if (req.method !== 'GET' || url.origin !== location.origin) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(req, { ignoreSearch: true });
    if (cached) return cached;
    try {
      const res = await fetch(req);
      if (res.ok && RUNTIME.test(url.pathname)) event.waitUntil(cache.put(url.pathname, res.clone()).catch(() => {}));
      return res;
    } catch {
      if (req.mode === 'navigate') return (await cache.match('index.html')) || Response.error();
      return Response.error();
    }
  })());
});
