// Offline support. precache.json (generated by tools/build-precache.mjs) lists the files the
// first level needs ("files", cached at install) and the rest ("lazy": other avatars' and areas'
// atlases, cached the first time the game fetches them, and in the background once play has
// begun: the "cache-rest" message below). BUILD is the content hash of the whole build; a new
// build installs into a fresh cache and drops the old one once it activates. Install requests
// bypass the browser's HTTP cache (cache: 'reload'), so a host's max-age can never put an older
// build's files under this build's key.
//
// Updates wait: there is no skipWaiting(), so a tab that is already open keeps the worker (and
// cache) of the build it started with, and a new build takes over once every tab of the game has
// been closed. Mixing old modules with new data is never possible. clients.claim() only affects
// the very first visit (no previous worker), so its page is served offline straight away.
const PREFIX = 'smw-';
const BUILD = '858a86039072'; // stamped by tools/build-precache.mjs so a new build reinstalls the worker
const CACHE = PREFIX + BUILD;
const RUNTIME = /\/data\//;    // same-origin paths cached on first use

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const res = await fetch(`precache.json?v=${BUILD}`, { cache: 'no-store' });
    const { files } = await res.json();
    const cache = await caches.open(CACHE);
    // Add in small batches so one slow file does not stall the whole install.
    for (let i = 0; i < files.length; i += 20) await cache.addAll(files.slice(i, i + 20).map(f => new Request(f, { cache: 'reload' })));
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k.startsWith(PREFIX) && k !== CACHE).map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

// Files the page fetched before this worker controlled it: on the very first visit the worker
// registers only as level 1 begins, so the splash, the menus, the cutscene and the shrinking
// zone were downloaded without it. Once it controls the page, the page posts the URLs it has
// loaded (main.js); the runtime-cached ones (/data/) missing from the cache are added, so every
// screen the player has seen also works offline.
self.addEventListener('message', event => {
  const msg = event.data;
  if (msg && msg.type === 'cache-rest') {
    if (!resting) resting = cacheRest().catch(() => {}).finally(() => { resting = null; });
    event.waitUntil(resting);
    return;
  }
  if (!msg || msg.type !== 'adopt' || !Array.isArray(msg.urls)) return;
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    for (const u of msg.urls) {
      let url;
      try { url = new URL(u, location.href); } catch { continue; }
      if (url.origin !== location.origin || !RUNTIME.test(url.pathname)) continue;
      if (await cache.match(url.pathname, { ignoreSearch: true })) continue;
      try {
        const res = await fetch(url.pathname);
        if (res.ok) await cache.put(url.pathname, res);
      } catch { /* offline again: the next visit's message tries again */ }
    }
  })());
});

// The rest of the game (precache.json "lazy": the other areas' and the other avatar's art, about
// 6 MB), fetched one file at a time when the page asks (main.js, a few seconds into the first
// level), so a player who loses the connection later (a car, a tunnel) can carry on to level 2
// and beyond. Not on a connection that asks to save data, and it stops as soon as the device goes
// offline; files already cached are skipped, so an interrupted run resumes on the next visit.
let resting = null;
async function cacheRest() {
  const conn = self.navigator && self.navigator.connection;
  if (conn && conn.saveData) return;
  const res = await fetch(`precache.json?v=${BUILD}`, { cache: 'no-store' });
  if (!res.ok) return;
  const { lazy = [] } = await res.json();
  const cache = await caches.open(CACHE);
  for (const f of lazy) {
    if (self.navigator && self.navigator.onLine === false) return;
    const path = new URL(f, self.registration.scope).pathname;
    if (await cache.match(path, { ignoreSearch: true })) continue;
    try {
      const r = await fetch(new Request(path, { cache: 'reload' }));
      if (r.ok) await cache.put(path, r);
    } catch { return; /* offline: the next visit tries again */ }
  }
}

self.addEventListener('fetch', event => {
  const req = event.request;
  const url = new URL(req.url);
  if (req.method !== 'GET' || url.origin !== location.origin) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(req, { ignoreSearch: true });
    if (cached) return cached;
    try {
      const res = await fetch(req);
      if (res.ok && RUNTIME.test(url.pathname)) event.waitUntil(cache.put(url.pathname, res.clone()).catch(() => {}));
      return res;
    } catch {
      if (req.mode === 'navigate') return (await cache.match('index.html')) || Response.error();
      return Response.error();
    }
  })());
});
